ALTER TABLE "Thread" ADD COLUMN IF NOT EXISTS "devTotalTimeSeconds" INTEGER NOT NULL DEFAULT 0; 
ALTER TABLE "Thread" ADD COLUMN IF NOT EXISTS "devChatTimeSeconds" INTEGER NOT NULL DEFAULT 0; 
ALTER TABLE "Rating" ALTER COLUMN "dimension1" DROP NOT NULL; 
ALTER TABLE "Rating" ALTER COLUMN "dimension2" DROP NOT NULL; 
ALTER TABLE "Rating" ALTER COLUMN "dimension3" DROP NOT NULL; 
